### ISSUE TITLE
pi-400 error

### ISSUE THREAD

**Issue by suyulin** [ardera/flutter-pi#143] opened 2021-01-13 13:34 UTC
![image](https://user-images.githubusercontent.com/6275411/104458930-f79c8080-55e6-11eb-9874-68656fae2430.png)

**Comment by ardera** [comment] 2021-01-21 21:33
Probably caused by the keyboard config errors. Flutter-pi really shouldn't segfault though

**Comment by ardera** [comment] 2021-01-21 21:37
should be fixed with #146

**Closed** 2021-01-21 21:37 UTC
