### ISSUE TITLE
How do i display the flutter app on the correct display? 

### ISSUE THREAD

**Issue by karticr** [ardera/flutter-pi#242] opened 2022-04-10 14:12 UTC
with a monitor connected along side the touch screen, the app always launches on the monitor instead of the touch screen.

**Comment by repentsinner** [comment] 2022-05-11 13:34
Dupe of #201?

**Comment by ardera** [comment] 2022-05-11 14:13
@repentsinner Yep you're right, closing this now

**Closed by ardera** 2022-05-11 14:13 UTC
